name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.9
  POETRY_VERSION: 1.5.1
  POETRY_URL: https://install.python-poetry.org
  POETRY_VIRTUALENVS_IN_PROJECT: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim-buster

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install System Dependencies
        run: |
          apt update && apt upgrade -y
          apt install -y make curl

      - name: Install Poetry
        run: |
          curl -sSL ${{ env.POETRY_URL }} | python - --version ${{ env.POETRY_VERSION }}
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          poetry --version

      - name: Install Packages with Poetry
        run: |
          poetry install --no-interaction

      - name: lint
        run: make lint

      - name: test
        run: make test

      - name: format
        run: make format

      - name: deploy
        run: make deploy
